### ISSUE TITLE
Are there plans to support CQL3 as CQL2 is being deprecated in cassandra 2.2 ?

### ISSUE THREAD

**Issue by macca129** [47deg/firebrand#50]

**Comment by raulraja** [comment]
@macca129 We don't have time to currently maintain this library since our focused changed to Scala at 47 Degrees. We are looking for active maintainers that would like to update the latest master to the current Cassandra version through new PRs. If you feel inclined to help out I'll make sure to review any PRs and include them in the codebase. Thanks.

**Comment by macca129** [comment]
Thanks Raul, 

I have an issue with setting the consistency level with the MAVEN obtained library.

The symptom is that the queries all appear to be issued with a consistency level of ALL
and even if I change the code to LOCAL_QUORUM or ONE the query fails to tolerate a single node failure.

This library doesn't contain the last changes in the latest jar file and unfortunately when I download the and add it to the project I get errors

Do you have a reference pattern for connecting and setting the consistency level with the currently published MAVEN library?

Many thanks in advance.

**Comment by macca129** [comment]
Hi Raul,
We have solved the consistency issue, 
thanks
